# Vscode http-buffer
# Works with the "REST Client" extension
# To install: Press F1, type "ext install" and choose 'Extensions: Install Extensions'  then search for rest-client.

## Set up variables for your google OpenID Connect (oidc) client, see EXERCISE.md for details
@client_id=REPLACE
@client_secret=REPLACE
@redirect_uri=https://my.example.com/oauth2callback

# The following request,after being updated with your client_id, should be performed manually in a web browser (ctrl+click)
# and will stop at a request where you find the code which value you can add to the @code variable below
GET https://accounts.google.com/o/oauth2/v2/auth?scope=profile+email+openid&response_type=code&redirect_uri=https://my.example.com/oauth2callback&client_id=REPLACE

# Log in and find your code in the browser's url when the login flow halts at an "The site can't be reached" error message

# The token you got in the last http request in your web browser:
@code=REPLACE

###  (Either) Token request CURL style
curl -X POST 
    --data grant_type="authorization_code"
    --data client_id={{client_id}} 
    --data client_secret={{client_secret}} 
    --data code={{code}}
    --data redirect_uri={{redirect_uri}}
    https://oauth2.googleapis.com/token


#### (Or) Token request HTTP-style
POST https://oauth2.googleapis.com/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id={{client_id}}
&client_secret={{client_secret}}
&code={{code}}
&redirect_uri={{redirect_uri}}


#### Token response will contain your id_token that can be inspected at https://jwt.io/ if you paste the value into the 'encoded' section


### BTW: Google's well-known openid configuration
GET https://accounts.google.com/.well-known/openid-configuration

