# IntelliJ IDEA - HTTP Client
# Only available in the 'ultimate edition' -> https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

# To install: Press F1, type "ext install" and choose 'Extensions: Install Extensions'  then search for rest-client.

# Set up variables for your google OpenID Connect (oidc) client, see EXERCISE.md for details
# Put the values in a file at the root of you IntelliJ IDEA module named 'rest-client.private.env.json'. Example file
#
#  "google": {
#    "client_id": "REPLACE",
#    "client_secret": "REPLACE",
#    "redirect_uri": "https://my.example.com/oauth2callback",
#    "code": "REPLACE_LATER"
#  }

# The following request,after being updated with your client_id, should be performed manually in a web browser (ctrl+click)
# and will stop at a request where you find the code which value you can add to the code variable in the 'rest-client.private.env.json' file (or hard code below)
GET https://accounts.google.com/o/oauth2/v2/auth?scope=profile+email+openid&response_type=code&redirect_uri=https://my.example.com/oauth2callback&client_id=20307596131-9voj36oeqb6mm11hho5bhqfbp75scpb3.apps.googleusercontent.com

# Log in and find your code in the browser's url when the login flow halts at an "The site can't be reached (Chrome)" error message

####  Token request HTTP-style (Run with google environment)
POST https://oauth2.googleapis.com/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id={{client_id}}&client_secret={{client_secret}}&code={{code}}&redirect_uri={{redirect_uri}}

#### Token response will contain your id_token that can be inspected at https://jwt.io/ if you paste the value into the 'encoded' section
# Ctrl + click to open in browser:
https://jwt.io/

### BTW: Google's well-known openid configuration
GET https://accounts.google.com/.well-known/openid-configuration

